/* Key identifiers */
export const KEY_IDS = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  FOUR: 'FOUR',
  FIVE: 'FIVE',
  SIX: 'SIX',
  SEVEN: 'SEVEN',
  EIGHT: 'EIGHT',
  NINE: 'NINE',
  ZERO: 'ZERO',
  DECIMAL: 'DECIMAL',
  ADD: 'ADD',
  SUBTRACT: 'SUBTRACT',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  EQUALS: 'EQUALS',
  OPEN_PARENTHESIS: 'OPEN_PARENTHESIS',
  CLOSE_PARENTHESIS: 'CLOSE_PARENTHESIS',
  CLEAR: 'CLEAR',
  DELETE: 'DELETE',
  MEMORY_CLEAR: 'MEMORY_CLEAR',
  MEMORY_ADD: 'MEMORY_ADD',
  MEMORY_SUBTRACT: 'MEMORY_SUBTRACT',
  MEMORY_RECALL: 'MEMORY_RECALL',
  SIN: 'SIN',
  COS: 'COS',
  TAN: 'TAN',
  SH: 'SH',
  CH: 'CH',
  TH: 'TH',
  E: 'E',
  PI: 'PI',
  POWER: 'POWER',
  SQRT: 'SQRT',
  LOG: 'LOG',
  LN: 'LN',
  ABS: 'ABS',
  FACT: 'FACT',
};

/** Key types */
export const KEY_TYPES = {
  NUMBER: 'NUMBER',
  OPERATION: 'OPERATION',
};

/* Key definitions */
export const KEYS = {
  [KEY_IDS.ONE]: { label: '1', value: '1', type: 'NUMBER' },
  [KEY_IDS.TWO]: { label: '2', value: '2', type: 'NUMBER' },
  [KEY_IDS.THREE]: { label: '3', value: '3', type: 'NUMBER' },
  [KEY_IDS.FOUR]: { label: '4', value: '4', type: 'NUMBER' },
  [KEY_IDS.FIVE]: { label: '5', value: '5', type: 'NUMBER' },
  [KEY_IDS.SIX]: { label: '6', value: '6', type: 'NUMBER' },
  [KEY_IDS.SEVEN]: { label: '7', value: '7', type: 'NUMBER' },
  [KEY_IDS.EIGHT]: { label: '8', value: '8', type: 'NUMBER' },
  [KEY_IDS.NINE]: { label: '9', value: '9', type: 'NUMBER' },
  [KEY_IDS.ZERO]: { label: '0', value: '0', type: 'NUMBER' },
  [KEY_IDS.DECIMAL]: { label: '.', value: '.', type: 'NUMBER' },
  [KEY_IDS.ADD]: { label: '+', value: '+', type: 'OPERATION', primary: true },
  [KEY_IDS.SUBTRACT]: { label: '-', value: '-', type: 'OPERATION', primary: true },
  [KEY_IDS.MULTIPLY]: { label: 'x', value: '*', type: 'OPERATION', primary: true },
  [KEY_IDS.DIVIDE]: { label: '÷', value: '/', type: 'OPERATION', primary: true },
  [KEY_IDS.EQUALS]: { label: '=', value: '=', primary: true },
  [KEY_IDS.OPEN_PARENTHESIS]: { label: '(', value: '(', type: 'OPERATION' },
  [KEY_IDS.CLOSE_PARENTHESIS]: { label: ')', value: ')', type: 'OPERATION' },
  [KEY_IDS.CLEAR]: { label: 'C', value: 'clear', type: 'OPERATION' },
  [KEY_IDS.DELETE]: { label: '⌫', value: 'delete', type: 'OPERATION' },
  [KEY_IDS.MEMORY_CLEAR]: { label: 'mc', value: 'mc', type: 'OPERATION' },
  [KEY_IDS.MEMORY_ADD]: { label: 'm+', value: 'm+', type: 'OPERATION' },
  [KEY_IDS.MEMORY_SUBTRACT]: { label: 'm-', value: 'm-', type: 'OPERATION' },
  [KEY_IDS.MEMORY_RECALL]: { label: 'mr', value: 'mr', type: 'OPERATION' },
  [KEY_IDS.SIN]: { label: 'sin', value: 'sin(', type: 'OPERATION' },
  [KEY_IDS.COS]: { label: 'cos', value: 'cos(', type: 'OPERATION' },
  [KEY_IDS.TAN]: { label: 'tan', value: 'tan(', type: 'OPERATION' },
  [KEY_IDS.SH]: { label: 'sh', value: 'sh(', type: 'OPERATION' },
  [KEY_IDS.CH]: { label: 'ch', value: 'ch(', type: 'OPERATION' },
  [KEY_IDS.TH]: { label: 'th', value: 'th(', type: 'OPERATION' },
  [KEY_IDS.E]: { label: 'e', value: 'e', type: 'OPERATION' },
  [KEY_IDS.PI]: { label: 'π', value: 'π', type: 'OPERATION' },
  [KEY_IDS.POWER]: { label: '^', value: '^', type: 'OPERATION' },
  [KEY_IDS.SQRT]: { label: '√', value: '√(', type: 'OPERATION' },
  [KEY_IDS.LOG]: { label: 'log', value: 'log(', type: 'OPERATION' },
  [KEY_IDS.LN]: { label: 'ln', value: 'ln(', type: 'OPERATION' },
  [KEY_IDS.ABS]: { label: 'abs', value: 'abs(', type: 'OPERATION' },
  [KEY_IDS.FACT]: { label: '!', value: 'fact(', type: 'OPERATION' },
}

/* Key panel layout */
export const KEY_PANEL = [
  // Row 1
  [
    KEY_IDS.MEMORY_CLEAR,
    KEY_IDS.MEMORY_ADD,
    KEY_IDS.MEMORY_SUBTRACT,
    KEY_IDS.MEMORY_RECALL,
    KEY_IDS.CLEAR,
    KEY_IDS.DELETE,
    KEY_IDS.POWER,
    KEY_IDS.DIVIDE,
  ],
  // Row 2
  [
    KEY_IDS.SQRT,
    KEY_IDS.POWER,
    KEY_IDS.OPEN_PARENTHESIS,
    KEY_IDS.CLOSE_PARENTHESIS,
    KEY_IDS.SEVEN,
    KEY_IDS.EIGHT,
    KEY_IDS.NINE,
    KEY_IDS.MULTIPLY,
  ],
  // Row 3
  [
    KEY_IDS.SIN,
    KEY_IDS.COS,
    KEY_IDS.TAN,
    KEY_IDS.E,
    KEY_IDS.FOUR,
    KEY_IDS.FIVE,
    KEY_IDS.SIX,
    KEY_IDS.SUBTRACT,
  ],
  // Row 4
  [
    KEY_IDS.SH,
    KEY_IDS.CH,
    KEY_IDS.TH,
    KEY_IDS.PI,
    KEY_IDS.ONE,
    KEY_IDS.TWO,
    KEY_IDS.THREE,
    KEY_IDS.ADD,
  ],
  // Row 5
  [
    KEY_IDS.ABS,
    KEY_IDS.LOG,
    KEY_IDS.LN,
    KEY_IDS.FACT,
    KEY_IDS.ZERO,
    KEY_IDS.DECIMAL,
    KEY_IDS.EQUALS,
  ],
];

export const KEY_PRESS_EVENT = 'key-press';